### ISSUE TITLE
Signup state selector too narrow to show the state names.

### ISSUE THREAD

**Issue by lleontan** [info442-group-7/HelpOut#27]
To replicate: When signing up for an account click on the box located to the right of the zip code input. If your screen is not wide enough the name or abbreviation of the state will be cut off making it very difficult to tell which state is being selected.

Reasoning: If the user cannot determine which state is their own, they will input a random state from the list to move on.

**Comment by jamiekiok** [comment]
Thanks so much for the feedback!

The selector is now wide enough to show all states. 

commit: [9f36446126a362372d9a57a47d772540ac443d00](https://github.com/info442-group-7/HelpOut/commit/9f36446126a362372d9a57a47d772540ac443d00)
