### ISSUE TITLE
The description field when creating a new issue is marked as optional when it is currently required to submit a new issue.

### ISSUE THREAD

**Issue by lleontan** [info442-group-7/HelpOut#28]
To replicate

* log in
* Click on the "new issue" button
* Fill out all of the inputs except the "description" field. Note that when one of the other fields is missing and the form is submitted a warning pops up reminding them that it is required.
* When clicking the submit button no warning will be displayed and an error in the console will appear. `Reference.set failed: First argument contains undefined in property 'REQUEST.-M91QH5G_eMb114G2Vd6.REQUEST_DESCRIPTION'`
* To fix: Fix the bug or make the field a required field.

Reasoning: If the field is not marked as required but it actually is because of a bug then the user may get confused about why the form does not submit.

Importance: Minor.

**Comment by jamiekiok** [comment]
Thanks so much for catching this! 

Made description a required field in df6f1c0
