### ISSUE TITLE
Minor: Task information discoverability 

### ISSUE THREAD

**Issue by magalj** [info442-group-7/HelpOut#29]
Task information
Minor
Description:
After clicking on the information icon for the task there is no way to return to the give up task or complete task buttons. 

**update I found that if you click on the information ie phone number and address you will return to those options
Reproduction:
1.	Click on My claimed tasks
2.	Click on the blue information button on the task options
3.	Return to options with reloading page or clicking on information

**Comment by kelsiej** [comment]
Hi,

Thanks for letting us know, we’ve updated the app so that on the card there is now a back button to return to all of the options after clicking more.

commit:1010e493b2bd9071b15f8cfac86665cc2b8f408c
