### ISSUE TITLE
MINOR: displaying error messages when signing in

### ISSUE THREAD

**Issue by angelashen0607** [info442-group-7/HelpOut#30]
**Description of issue:**
The sign in/up page doesn't show any error messages when a correctly formatted but not registered email is being entered.

**Reproduction of steps:**

1. Type in random email format and random password
2. Click log in 

**Rationale:**
I think this is important because some users might have already registered an account but type in the wrong password. In that case, the user would probably think that the webpage breaks because it is not showing any error msg nor is the webpage changing. Thus, they will not proceed to the main function of this web app.

**Comment by pranita122** [comment]
Definitely something we would have fixed if we had more time, but as this particular message is not within the scope of our requirements for this release, we chose to not prioritize it.
