### ISSUE TITLE
Minor: Logged in state is appearing when it shouldn't be

### ISSUE THREAD

**Issue by ashleyvarma** [info442-group-7/HelpOut#31]
Reproduction Steps:
1. Enter website on login page

Description: 
When no account is logged in, there is still an option to log out stated under the "Welcome Back!" dropdown.

Rationale:
This isn't very problematic, it's more of a matter of refining a small detail. Functionally when it is clicked, nothing changes as it still leads to the login page on the web app. One suggestion I have about this is to consider setting the state of the Welcome Back area to false when on the immediate login/landing page.

![image](https://user-images.githubusercontent.com/26805404/83845866-7f6bf500-a6be-11ea-920a-334375fe36ef.png)

**Comment by pranita122** [comment]
issue fixed!
