### ISSUE TITLE
[Minor]Homepage welcome page should be HelpOut?

### ISSUE THREAD

**Issue by gcaelin30** [info442-group-7/HelpOut#32]
<img width="1280" alt="Screen Shot 2020-06-04 at 11 55 39 PM" src="https://user-images.githubusercontent.com/17754353/83846111-eee1e480-a6be-11ea-9473-0caab30be4d9.png">
Super minor but have the brand name logo be the same as the name on the homepage screen
I absolutely love that you guys had put "Sign Up" right in front of the user's face! That's like a normal thing to have done but the other sites are like NO SIGN UP! JUST SIGN IN! (think of that dog meme no get ball just throw)

**Comment by pranita122** [comment]
Fixed issue!
