### ISSUE TITLE
MINOR: sign up form doesn't indicate required inputs accurately

### ISSUE THREAD

**Issue by rachelvuu** [info442-group-7/HelpOut#33]
**Description of the issue:**
Appears that required fields are marked by an asterisk (such as for password), however when the user doesn't enter other required fields such as address, an error appears. For address, another minor issue is that it displays "Your full address is required." for each part of the address that is not filled in. This should either read only once until the user inputs their entire address, or display an error for each input that is missing (street, city, zip). 

**Reproduction of steps:**
1. Sign up for an account
2. Skip fields that are not marked as required
3. See error messages displayed

**Supporting images:**

![image](https://user-images.githubusercontent.com/32352509/83925153-52115c80-a73b-11ea-85b8-c99e719dcc76.png)

**Rationale:**
This is just a minor issue that makes it unclear to users what is and is not required. It should be really simple to fix (just adding asterisks to the form and displaying "Your full address is required." only once). I liked the idea of this application and it was executed very well—good job!

**Comment by jamiekiok** [comment]
Thanks so much for catching this and for your feedback! :-)

Fixed this issue in [commit e3c9805](https://github.com/info442-group-7/HelpOut/commit/9f36446126a362372d9a57a47d772540ac443d00).
