### ISSUE TITLE
MINOR: User/author can claim a task they created

### ISSUE THREAD

**Issue by AlexanderES** [info442-group-7/HelpOut#36]
After creating a new task I needed help with, I am also able to claim it, hiding it from other users. I'm not sure if this may just have something to do with the requirements of the project though

1. Login to your account
2. Click on the Create new request button
3. Fill out all the fields of the request (what do you need help with, additional details, address, zip code)
4. Click Submit
5. Click Done on the popup
6. Hover over Tasks on the navbar
7. Click Find new tasks 
8. Click the claim/plus button on your task
9. Login into another account and click the Find more tasks button or access Find more tasks in the navbar under Tasks. You can also just go back to find new tasks with your original account
10. The task will be missing from this page so other people aren't able to help with the task 

I was thinking the web app would be more about helping other people so I was expecting not to be able to claim my own tasks to help. The user can already delete their task if they don't need help with it so it seems like they don't really need to claim the task to get rid of it, and it kind of changes the purpose of the app since they may just use it as a personal task list. The user may only need to claim tasks of other users

**Comment by kelsiej** [comment]
Hi,

We’ve updated the app so that users no longer have their own tasks show up when finding a new task. Thanks for the feedback!

commit:c709123169873970e3db6309b411197a68a17b4a
