### ISSUE TITLE
MINOR: Wrong navbar link is highlighted when and after creating a request

### ISSUE THREAD

**Issue by AlexanderES** [info442-group-7/HelpOut#37]
After creating a request, the app takes you to the "My Requests" page but instead of "Requests" being highlighted blue and having the blue line under it, the Tasks link in the navbar is highlighted instead. After testing it again, it seems like Tasks becomes highlighted right after clicking Create new Request

1. Login in to your account
2. Click on Create new Request
3. If you look at the top on the navbar, Tasks becomes highlighted
4. Fill out all the fields of the request (what do you need help with, additional details, address, zip code)
5. Click submit
6. Click done on the popup message
7. Tasks will still be highlighted on the navbar

**Expected behavior**
Since I clicked on Create new request, I thought I would be under the Requests section. After hovering over requests and seeing the drop-down, it seemed like Requests was meant to be highlighted instead of Tasks. This may confuse users since they may not know where the different links are located since they are not highlighted even when they are on those pages/links. The routing in the app seems fine though!

**Comment by pranita122** [comment]
Turned out to be a bug within AntD's provided code (checked our states for each route and matched to the appropriate menu tab). We are unable to fix this issue for this first release.
