### ISSUE TITLE
Minor: Create an account input fields

### ISSUE THREAD

**Issue by rsgoertz** [info442-group-7/HelpOut#38]
On the create an account input form:

The Zip Code field allows non-numeric characters

**Comment by jamiekiok** [comment]
Hi, thanks so much for pointing this out! 

The 'create account' page no longer allows non-numeric characters to be added.

commit: [9f36446126a362372d9a57a47d772540ac443d00](https://github.com/info442-group-7/HelpOut/commit/9f36446126a362372d9a57a47d772540ac443d00)
